export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  devices: "/devices",
  deviceDetail: (id: string | number) => `/devices/${id}`,
  rules: "/rules",
  ruleDetail: (id: string | number) => `/rules/${id}`,
  scheduler: "/scheduler",
  logger: "/logger",
  indexing: "/indexing",
  admins: "/admin",
  profile: "/my-profile",
  profileEdit: (userId: string | number) => `/my-profile/edit/${userId}`,
  settings: "/settings",
  chat: "/chat",
} as const;
